### PR TITLE
Add features for denite.nvim

### PR DESCRIPTION
**Pull request by delphinus**
This adds features for [denite.nvim][] to open a new term, preview, and select one. I tested with both Neovim / Vim8.

[denite.nvim]: https://github.com/Shougo/denite.nvim

If you like it, I will add some docs for this.

BhAYdTKc1Y

### CODE REVIEW

**Comment by voldikss** [comment]
Awesome!

**Comment by voldikss** [comment]
Hi @delphinus excuse me.

I was refactoring the plugin recently. And I have been thinking about putting fuzzy finder related feature (i.e. denite and clap) out of the plugin repo and organize them into independent repos. Since there are already some other fuzzy finder extensions of this plugin such as LeaderF-floaterm and fzf-floaterm which is in their own repos. Detaching and reorganizing would making this repo clearer.

I would like to listen to your thoughts.

**Comment by delphinus** [comment]
@voldikss  Agree. It become easy to maintain if do so. Then, which org will be used for the separated repo?

**Comment by voldikss** [comment]
An org would make a big fuss. I simplily feel that people-owned repo is enough. What do you think?

**Comment by delphinus** [comment]
Sure, it seems no problem. I'll make dephinus/fzf-denite and move these codes, is it OK?

**Comment by voldikss** [comment]
> Sure, it seems no problem. I'll make dephinus/fzf-denite and move these codes, is it OK?

Yes, it would be great. BTW, do you mean `denite-floaterm`?

**Comment by delphinus** [comment]
Oh, I've mistaken 😆 I'll use `denite-floaterm`

**Comment by voldikss** [comment]
Hi @delphinus are you ready for the new repo denite-floaterm? I decided to remove clap and denite code from this repo. :eyes:

**Comment by delphinus** [comment]
Thank you. Now I see the new repo: denite-floaterm. I'll check it.

**Comment by voldikss** [comment]
Thanks you. I'll merge #262 after you make denite-floaterm public.

**Comment by voldikss** [comment]
@delphinus you forgot to make that repo pubic🙈

**Comment by delphinus** [comment]
Sorry. I did now. Later I'll add more doc and screenshots ;)

**Pull request merged**
