### PR TITLE
Fix #162

### LINKED ISSUE #162: FloatermNew --name=xxx leaves an unlisted buffer after closing that floaterm instance.
- Please make sure you have looked through the [F.A.Q.](https://github.com/voldikss/vim-floaterm/#faq) first.

- Please make sure you are using the latest version of the plugin.

- Please use English as far as possible.

### To Reproduce

- Steps to reproduce the behavior:
  1. `:FloatermNew --name=test`
  2. After opening floaterm, type `:ls~` and there would be two terminal instances:
        ```
          3u hR  "floaterm://test"              line 0
          5u     "term:///mnt/repo//13635:/usr/bin/zsh" line 1
        ```
       But there should be just one --- the `floaterm://` instance

  3. Close it either using `<C-d>` or `:FloatermKill`
  4. Type `:ls!`, the terminal instance `term:///mnt/repo//13635:/usr/bin/zsh` still is there...

It's caused by this line, https://github.com/voldikss/vim-floaterm/blob/9e8d68d457b67cf55ccfaa9ff14c891a79114db3/autoload/floaterm/terminal.vim#L40

However, adding `0file` above that line doesn't solve the problem....

### PR DESCRIPTION
**Pull request by adigitoleo**
Fix unwanted unlisted terminals as per #162

### CODE REVIEW

**Comment by adigitoleo** [comment]
Sorry for the mess, I should have run the tests locally.

**Comment by adigitoleo** [comment]
Nah I'll try again.

**Comment by adigitoleo** [comment]
I'm not sure why, but the last test was taking a long time. Maybe it's normal and I just got spooked.

**Comment by adigitoleo** [comment]
Phew, OK looks good now :)

**Comment by voldikss** [comment]
> I'm not sure why, but the last test was taking a long time. Maybe it's normal and I just got spooked.

Yes, the checking is OK. CI failure is not related to this PR. It must be caused by vader.vim.

Thanks for this PR, I'll check it soon.

**Comment by voldikss** [comment]
Merged, thank you very much! :+1:

**Pull request merged**
