### PR TITLE
Clean up code for the new API

### PR DESCRIPTION
**Pull request by delphinus**
This removes the odd method to load modules that have common funcs. The main purpose for this is to call the dict function `g:floaterm.foo()`, the old API.

Now it can call the API with more robust way: `self.vim.call('floaterm#foo()'`. So I rewrote the whole code for Denite.

# TODO

* [x] We can execute any commands with `Denite floaterm:new:'ls -l'` ? 🤔
  - I will not implement here. It does not have much meanings.
* [x] more dog fooding

### CODE REVIEW

**Comment by voldikss** [comment]
Awesome!

**Comment by voldikss** [comment]
> We can execute any commands with Denite floaterm:new:'ls -l'

Sorry I am not farmiliar with denite.nvim. Is this a command that can be executed in the denite buffer? Why we need this command since we already have the `FloatermNew` command?

**Comment by voldikss** [comment]
> more dog fooding

Sorry I am not a native English speaker, could you explain that for me?

**Comment by delphinus** [comment]
> Why we need this command since we already have the FloatermNew command?

Indeed. It is meaningless Denite has this feature 😆 

> more dog fooding

I used this with the meaning that this code might have any bug and I myself should use more time, 1 or 2 day(s). Then I will press “Ready for review”.

**Comment by voldikss** [comment]
Thansk for your explains!

BTW, I tried `:Denite floaterm:new:'ls -l'` but no floaterm was opened. Is there anything wrong?
denite_floaterm

**Comment by delphinus** [comment]
No, sorry I have not implement this yet.

If the user want to show up and action with the results from a CLI command, he/she can use `Denite output:'ls -l'`. So I plan on not implement this here.

**Comment by delphinus** [comment]
Fixed small bugs for the preview action. 1966b7c, b0abce2

**Comment by delphinus** [comment]
and it seems bugs to be removed, I think. Ready to merge.

**Pull request merged**
